### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by gabriel-del** [danman113/simple-autoscrollv2#6]
Loading the extension on the browser, give the error:

**Failed to load extension**
```
File
~/Downloads/simple-autoscrollv2-main
Error
Could not load background script 'scripts/background.js'.
Could not load manifest.
```

**Comment by danman113** [comment]
Hey, because this is a typescript project you have to actually build the javascript assets. I'll add instructions to the readme

**Comment by danman113** [comment]
Instructions have been added. You can find them at https://github.com/danman113/simple-autoscrollv2#setup

**Comment by gabriel-del** [comment]
Thank you! Your first version is great, I'm going to take a look on this one
